// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: person.proto

package person

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Person_EyeColor int32

const (
	Person_UNKNOWN_EYE_COLOR Person_EyeColor = 0
	Person_BLUE_COLOR        Person_EyeColor = 1
	Person_GREEN_COLOR       Person_EyeColor = 2
	Person_BROWN_COLOR       Person_EyeColor = 3
	Person_BLACK_COLOR       Person_EyeColor = 4
)

var Person_EyeColor_name = map[int32]string{
	0: "UNKNOWN_EYE_COLOR",
	1: "BLUE_COLOR",
	2: "GREEN_COLOR",
	3: "BROWN_COLOR",
	4: "BLACK_COLOR",
}

var Person_EyeColor_value = map[string]int32{
	"UNKNOWN_EYE_COLOR": 0,
	"BLUE_COLOR":        1,
	"GREEN_COLOR":       2,
	"BROWN_COLOR":       3,
	"BLACK_COLOR":       4,
}

func (x Person_EyeColor) String() string {
	return proto.EnumName(Person_EyeColor_name, int32(x))
}

func (Person_EyeColor) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_4c9e10cf24b1156d, []int{0, 0}
}

// 1-15 fields are most used field uses 1 byte
//2-2047 is not so used fields 2 bytes
type Person struct {
	//Auto-populated field
	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// Firstname of the person
	Firstname string `protobuf:"bytes,2,opt,name=Firstname,proto3" json:"Firstname,omitempty"`
	// Last name of the person
	Lastname string `protobuf:"bytes,3,opt,name=Lastname,proto3" json:"Lastname,omitempty"`
	// Age of the person
	Age int32 `protobuf:"varint,4,opt,name=age,proto3" json:"age,omitempty"`
	// Is his name verified
	IsVerified bool `protobuf:"varint,5,opt,name=is_verified,json=isVerified,proto3" json:"is_verified,omitempty"`
	//profile image of the picture
	Picture              []byte          `protobuf:"bytes,6,opt,name=picture,proto3" json:"picture,omitempty"`
	PhoneNumber          []string        `protobuf:"bytes,7,rep,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	EyeColor             Person_EyeColor `protobuf:"varint,8,opt,name=eye_color,json=eyeColor,proto3,enum=Person_EyeColor" json:"eye_color,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Person) Reset()         { *m = Person{} }
func (m *Person) String() string { return proto.CompactTextString(m) }
func (*Person) ProtoMessage()    {}
func (*Person) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c9e10cf24b1156d, []int{0}
}
func (m *Person) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Person.Unmarshal(m, b)
}
func (m *Person) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Person.Marshal(b, m, deterministic)
}
func (m *Person) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Person.Merge(m, src)
}
func (m *Person) XXX_Size() int {
	return xxx_messageInfo_Person.Size(m)
}
func (m *Person) XXX_DiscardUnknown() {
	xxx_messageInfo_Person.DiscardUnknown(m)
}

var xxx_messageInfo_Person proto.InternalMessageInfo

func (m *Person) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Person) GetFirstname() string {
	if m != nil {
		return m.Firstname
	}
	return ""
}

func (m *Person) GetLastname() string {
	if m != nil {
		return m.Lastname
	}
	return ""
}

func (m *Person) GetAge() int32 {
	if m != nil {
		return m.Age
	}
	return 0
}

func (m *Person) GetIsVerified() bool {
	if m != nil {
		return m.IsVerified
	}
	return false
}

func (m *Person) GetPicture() []byte {
	if m != nil {
		return m.Picture
	}
	return nil
}

func (m *Person) GetPhoneNumber() []string {
	if m != nil {
		return m.PhoneNumber
	}
	return nil
}

func (m *Person) GetEyeColor() Person_EyeColor {
	if m != nil {
		return m.EyeColor
	}
	return Person_UNKNOWN_EYE_COLOR
}

func init() {
	proto.RegisterEnum("Person_EyeColor", Person_EyeColor_name, Person_EyeColor_value)
	proto.RegisterType((*Person)(nil), "Person")
}

func init() { proto.RegisterFile("person.proto", fileDescriptor_4c9e10cf24b1156d) }

var fileDescriptor_4c9e10cf24b1156d = []byte{
	// 280 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x44, 0xd0, 0xdf, 0x4a, 0xf3, 0x30,
	0x18, 0x06, 0xf0, 0x2f, 0xed, 0xfe, 0xb4, 0xef, 0xc6, 0xbe, 0x1a, 0x10, 0x82, 0x08, 0xc6, 0x1d,
	0xe5, 0xc4, 0x1e, 0xe8, 0x15, 0xb8, 0x52, 0x3d, 0x58, 0x69, 0x25, 0x30, 0xc5, 0xa3, 0xd2, 0xad,
	0xaf, 0x1a, 0x70, 0x4d, 0x49, 0x3b, 0x61, 0x57, 0xea, 0xed, 0x48, 0xb3, 0x56, 0xcf, 0x9e, 0xe7,
	0xf7, 0x90, 0x40, 0x02, 0xf3, 0x1a, 0x4d, 0xa3, 0xab, 0xb0, 0x36, 0xba, 0xd5, 0xcb, 0x6f, 0x07,
	0x26, 0x4f, 0x16, 0xe8, 0x02, 0x1c, 0x55, 0x32, 0xc2, 0x89, 0x18, 0x4b, 0x47, 0x95, 0xf4, 0x12,
	0xfc, 0x07, 0x65, 0x9a, 0xb6, 0x2a, 0xf6, 0xc8, 0x1c, 0x4e, 0x84, 0x2f, 0xff, 0x80, 0x5e, 0x80,
	0x97, 0x14, 0xfd, 0xe8, 0xda, 0xf1, 0xb7, 0xd3, 0x00, 0xdc, 0xe2, 0x1d, 0xd9, 0xc8, 0x5e, 0xd5,
	0x45, 0x7a, 0x05, 0x33, 0xd5, 0xe4, 0x5f, 0x68, 0xd4, 0x9b, 0xc2, 0x92, 0x8d, 0x39, 0x11, 0x9e,
	0x04, 0xd5, 0x3c, 0xf7, 0x42, 0x19, 0x4c, 0x6b, 0xb5, 0x6b, 0x0f, 0x06, 0xd9, 0x84, 0x13, 0x31,
	0x97, 0x43, 0xa5, 0xd7, 0x30, 0xaf, 0x3f, 0x74, 0x85, 0x79, 0x75, 0xd8, 0x6f, 0xd1, 0xb0, 0x29,
	0x77, 0x85, 0x2f, 0x67, 0xd6, 0x52, 0x4b, 0xf4, 0x06, 0x7c, 0x3c, 0x62, 0xbe, 0xd3, 0x9f, 0xda,
	0x30, 0x8f, 0x13, 0xb1, 0xb8, 0x0d, 0xc2, 0xd3, 0xab, 0xc2, 0xf8, 0x88, 0x51, 0xe7, 0xd2, 0xc3,
	0x3e, 0x2d, 0x4b, 0xf0, 0x06, 0xa5, 0xe7, 0x70, 0xb6, 0x49, 0xd7, 0x69, 0xf6, 0x92, 0xe6, 0xf1,
	0x6b, 0x9c, 0x47, 0x59, 0x92, 0xc9, 0xe0, 0x1f, 0x5d, 0x00, 0xac, 0x92, 0xcd, 0xd0, 0x09, 0xfd,
	0x0f, 0xb3, 0x47, 0x19, 0xc7, 0x69, 0x0f, 0x4e, 0x07, 0x2b, 0xd9, 0x9d, 0x3a, 0x81, 0x6b, 0x21,
	0xb9, 0x8f, 0xd6, 0x3d, 0x8c, 0xb6, 0x13, 0xfb, 0xc1, 0x77, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff,
	0x56, 0xfb, 0x6e, 0x01, 0x70, 0x01, 0x00, 0x00,
}
